trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
pr:
  branches:
    include:
      - main

variables:
  - group: sonarqube
  - group: sign
  - group: ossrh
  - group: gradle_plugin_portal

resources:
  repositories:
    - repository: templates
      type: github
      name: bakdata/bakdata-project-templates
      ref: feature/disable-sonar
      endpoint: bot

jobs:
  - template: azure/gradle/build.yml@templates
    parameters:
      assessCode: 'false' # Requires Java 17
  - template: azure/gradle/create_tag_version.yml@templates
  - template: azure/gradle/upload_release.yml@templates
    parameters:
      plugin: 'true'
  - template: azure/gradle/upload_snapshot.yml@templates
